defaults:
  - _self_
  # Specifies the dataparser used to unpack the data. AnnotatedDataParserUnion
  - dataparser: replica.yaml
  # - dataparser: replica_rgbsem.yaml
  # Specifies the camera pose optimizer used during training. Helpful if poses are noisy,
  # such as for data from Record3D. CameraOptimizerConfig
  - camera: off.yaml

# Dataset directory
data_dir: ${data_dir}

# Class name
name: semantic

# Number of rays per batch to use per training iteration. int
train_num_rays_per_batch: 1024
# Number of images to sample during training iteration. int
train_num_images_to_sample_from: -1
# When not training on all images, number of iterations before picking new
# images. If -1, never pick new images. int
train_num_times_to_repeat_images: -1

# Number of rays per batch to use per eval iteration. int
eval_num_rays_per_batch: 1024
# Number of images to sample during eval iteration. int
eval_num_images_to_sample_from: -1
# When not evaluating on all images, number of iterations before picking
# new images. If -1, never pick new images. int
eval_num_times_to_repeat_images: -1
# Specifies the image indices to use during eval; if None, uses all.  Optional[Tuple[int, ...]]
eval_image_indices: [0,]

# The scale factor for scaling spatial data such as images, mask, semantics
# along with relevant information about camera intrinsics. float
camera_res_scale_factor: 1.0
